// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManagementBackend.Models;

#nullable disable

namespace RestaurantManagementBackend.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20251129123308_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantManagementBackend.Models.UserDbContext+MenuItem", b =>
                {
                    b.Property<string>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("CategoryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("RestaurantManagementBackend.Models.UserDbContext+User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("emailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("mobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            createdDate = new DateTime(2025, 11, 29, 19, 3, 6, 889, DateTimeKind.Local).AddTicks(8339),
                            emailId = "admin@example.com",
                            fullName = "System Admin",
                            isActive = true,
                            mobileNo = "0912345678",
                            passwordHash = "$2a$11$HpheXDz2T5mtzPYjYxZ83uJKUssgpjch3Qr94uKT2iznROkflXgOO",
                            role = "Admin",
                            userName = "Admin"
                        },
                        new
                        {
                            userId = 2,
                            createdDate = new DateTime(2025, 11, 29, 19, 3, 6, 889, DateTimeKind.Local).AddTicks(8355),
                            emailId = "manager@example.com",
                            fullName = "Restaurant Manager",
                            isActive = true,
                            mobileNo = "0987654321",
                            passwordHash = "$2a$11$5gapJTxVbsDMWDbKlvFvdeashZeGobP5wzVU/xURWdC1Aj4noub8u",
                            role = "Manager",
                            userName = "Manager"
                        },
                        new
                        {
                            userId = 3,
                            createdDate = new DateTime(2025, 11, 29, 19, 3, 6, 889, DateTimeKind.Local).AddTicks(8356),
                            emailId = "casher@example.com",
                            fullName = "Main Casher",
                            isActive = true,
                            mobileNo = "09911223344",
                            passwordHash = "$2a$11$OBmUZz95Vbnt59Mw/4yZf.jRGnRNUr6ENTfXNPlMz19BwySu0Xa4q",
                            role = "Casher",
                            userName = "Casher"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
